"""Backend module for db2."""

# ============================================================
# Adapter
# ============================================================

from ..backend_base import adapters, with_connection_or_raise
from ..backend_base import SQLAdapter


class DB2(SQLAdapter):
    """
    Base DB2 adapter — shared logic for both driver variants.

    Trailing ``;`` is stripped from statements (DB2 rejects it).
    ``lastrowid`` reads ``IDENTITY_VAL_LOCAL()`` from the table.
    Slicing happens client-side in ``rowslice`` since DB2 has no
    ``LIMIT``/``OFFSET`` in older releases.
    """

    dbengine = "db2"

    def _initialize_(self):
        """Stash the raw connection-string portion of the URI."""
        super()._initialize_()
        self.ruri = self.uri.split("://", 1)[1]

    @with_connection_or_raise
    def execute(self, *args, **kwargs):
        """
        Execute a statement, stripping the trailing ``;`` DB2 rejects.

        Accepts ``placeholders=`` in kwargs (pydal convention) and
        appends them as a positional arg.
        """
        args = list(args)
        command = self.filter_sql_command(args[0])
        if command[-1:] == ";":
            command = command[:-1]
        handlers = self._build_handlers_for_execution()
        for handler in handlers:
            handler.before_execute(command)
        # ``args`` was previously a tuple; ``.append`` would raise
        # AttributeError whenever placeholders were supplied.
        if kwargs.get("placeholders"):
            args.append(kwargs["placeholders"])
            del kwargs["placeholders"]
        rv = self.cursor.execute(command, *args[1:], **kwargs)
        for handler in handlers:
            handler.after_execute(command)
        return rv

    def lastrowid(self, table):
        """Return the most-recent IDENTITY via ``IDENTITY_VAL_LOCAL()``."""
        self.execute(
            "SELECT DISTINCT IDENTITY_VAL_LOCAL() FROM %s;" % table._rname
            if table._rname
            else table
        )
        return int(self.cursor.fetchone()[0])

    def rowslice(self, rows, minimum=0, maximum=None):
        """Client-side slice — DB2 ``LIMIT``/``OFFSET`` isn't universal."""
        if maximum is None:
            return rows[minimum:]
        return rows[minimum:maximum]

    def test_connection(self):
        """Ping with the standard DB2 ``SYSIBM.SYSDUMMY1`` smoke query."""
        self.execute("select * from sysibm.sysdummy1")


@adapters.register_for("db2:ibm_db_dbi")
class DB2IBM(DB2):
    """DB2 via the IBM-supplied ``ibm_db_dbi`` Python driver."""

    drivers = ("ibm_db_dbi",)

    def connector(self):
        """Parse ``DSN=...;UID=...;PWD=...`` and open the connection."""
        uriparts = self.ruri.split(";")
        cnxn = {}
        for var in uriparts:
            v = var.split("=")
            cnxn[v[0].lower()] = v[1]
        return self.driver.connect(
            cnxn["dsn"], cnxn["uid"], cnxn["pwd"], **self.driver_args
        )


@adapters.register_for("db2:pyodbc")
class DB2Pyodbc(DB2):
    """DB2 via pyodbc. Forces UTF-8 client encoding."""

    drivers = ("pyodbc",)

    def connector(self):
        """Open the pyodbc connection and force UTF-8 client encoding."""
        conn = self.driver.connect(self.ruri, **self.driver_args)
        conn.setencoding(encoding="utf-8")
        return conn

# ============================================================
# Dialect
# ============================================================

from ..backend_base import dialects, sqltype_for
from ..backend_base import SQLDialect


@dialects.register_for(DB2)
class DB2Dialect(SQLDialect):
    """
    DB2 dialect.

    Pagination uses ``ROW_NUMBER() OVER (...)`` wrappers. Text columns
    map to ``CLOB``. Synthetic IDs use ``GENERATED BY DEFAULT AS
    IDENTITY``; ``lastrowid`` reads ``IDENTITY_VAL_LOCAL()``.
    """

    @sqltype_for("text")
    def type_text(self):
        """DB2 has no TEXT type; map to CLOB."""
        return "CLOB"

    @sqltype_for("integer")
    def type_integer(self):
        """DB2 INTEGER as ``INT`` (4-byte signed)."""
        return "INT"

    @sqltype_for("bigint")
    def type_bigint(self):
        return "BIGINT"

    @sqltype_for("float")
    def type_float(self):
        return "REAL"

    @sqltype_for("id")
    def type_id(self):
        return "INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL"

    @sqltype_for("big-id")
    def type_big_id(self):
        return "BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL"

    @sqltype_for("reference")
    def type_reference(self):
        return (
            "INT, FOREIGN KEY (%(field_name)s) REFERENCES "
            + "%(foreign_key)s ON DELETE %(on_delete_action)s"
        )

    @sqltype_for("big-reference")
    def type_big_reference(self):
        return (
            "BIGINT, FOREIGN KEY (%(field_name)s) REFERENCES "
            + "%(foreign_key)s ON DELETE %(on_delete_action)s"
        )

    @sqltype_for("reference FK")
    def type_reference_fk(self):
        return (
            ", CONSTRAINT FK_%(constraint_name)s FOREIGN KEY "
            + "(%(field_name)s) REFERENCES %(foreign_key)s "
            + "ON DELETE %(on_delete_action)s"
        )

    @sqltype_for("reference TFK")
    def type_reference_tfk(self):
        return (
            " CONSTRAINT FK_%(constraint_name)s_PK FOREIGN KEY "
            + "(%(field_name)s) REFERENCES %(foreign_table)s"
            + "(%(foreign_key)s) ON DELETE %(on_delete_action)s"
        )

    def left_join(self, val, query_env={}):
        # Left join must always have an ON clause
        if not isinstance(val, str):
            val = self.expand(val, query_env=query_env)
        return "LEFT OUTER JOIN %s" % val

    @property
    def random(self):
        return "RAND()"

    def select(
        self,
        fields,
        tables,
        where=None,
        groupby=None,
        having=None,
        orderby=None,
        limitby=None,
        distinct=False,
        for_update=False,
        with_cte=None,
    ):
        dst, whr, grp, order, limit, offset, upd = "", "", "", "", "", "", ""
        if distinct is True:
            dst = " DISTINCT"
        elif distinct:
            dst = " DISTINCT ON (%s)" % distinct
        if where:
            whr = " %s" % self.where(where)
        if groupby:
            grp = " GROUP BY %s" % groupby
            if having:
                grp += " HAVING %s" % having
        if orderby:
            order = " ORDER BY %s" % orderby
        if limitby:
            (lmin, lmax) = limitby
            limit = " FETCH FIRST %i ROWS ONLY" % lmax
        if for_update:
            upd = " FOR UPDATE"

        if with_cte:
            recursive, cte = with_cte
            recursive = " RECURSIVE" if recursive else ""
            with_cte = "WITH%s %s " % (recursive, cte)
        else:
            with_cte = ""

        return "%sSELECT%s %s FROM %s%s%s%s%s%s%s;" % (
            with_cte,
            dst,
            fields,
            tables,
            whr,
            grp,
            order,
            limit,
            offset,
            upd,
        )

# ============================================================
# Representer
# ============================================================

import base64
import datetime

from ..utils import to_bytes
from ..backend_base import representers
from ..backend_base import SQLRepresenter


@representers.register_for(DB2)
class DB2Representer(SQLRepresenter):
    """DB2-specific value rendering for ``blob`` and ``datetime``."""

    def exceptions(self, obj, field_type):
        """Render BLOBs via ``BLOB(...)`` and datetimes in DB2's dotted format."""
        if field_type == "blob":
            # DB2 wants base64-wrapped blobs; b64encode needs bytes input.
            obj = base64.b64encode(to_bytes(obj)).decode("ascii")
            return "BLOB('%s')" % obj
        if field_type == "datetime":
            if isinstance(obj, datetime.datetime):
                obj = obj.isoformat()[:19].replace("T", "-").replace(":", ".")
            elif isinstance(obj, datetime.date):
                obj = obj.isoformat()[:10] + "-00.00.00"
            return "'%s'" % obj
        return None

